"""add_incident_performance_tracking_fields

Revision ID: 1e17c460da18
Revises: 0003
Create Date: 2026-05-25 05:53:17.751727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('resolved_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'incidents', 'users', ['resolved_by_id'], ['user_id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_phone_codes_user_id'), table_name='phone_verification_codes')
    op.create_index(op.f('ix_phone_verification_codes_user_id'), 'phone_verification_codes', ['user_id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_phone_verification_codes_user_id'), table_name='phone_verification_codes')
    op.create_index(op.f('ix_phone_codes_user_id'), 'phone_verification_codes', ['user_id'], unique=False)
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'resolved_by_id')
    op.drop_column('incidents', 'resolved_at')
    # ### end Alembic commands ###
